#!/bin/bash

# GitHub Repository Setup Script
# Run this after creating your GitHub repository

echo "🚀 Setting up GitHub repository connection..."
echo ""
echo "IMPORTANT: First create a new repository on GitHub.com"
echo "  1. Go to https://github.com/new"
echo "  2. Name: data-science-classroom (or your choice)"
echo "  3. Description: Complete database collection for data science education"
echo "  4. Make it PUBLIC (required for GitHub Classroom)"
echo "  5. DO NOT add README, .gitignore, or license"
echo "  6. Click 'Create repository'"
echo ""
echo "Then replace YOUR_USERNAME and YOUR_REPO_NAME below and run:"
echo ""
echo "# Connect to your new repository:"
echo "git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO_NAME.git"
echo "git push -u origin main"
echo ""
echo "Example:"
echo "git remote add origin https://github.com/humphrjk-utsa/data-science-classroom.git"
echo "git push -u origin main"
echo ""
echo "Your repository is ready with:"
echo "✅ 8 comprehensive databases"
echo "✅ Automated setup scripts"
echo "✅ Complete documentation"
echo "✅ GitHub Classroom ready"
echo ""
echo "Next steps after pushing:"
echo "1. Test with a new Codespace"
echo "2. Create GitHub Classroom assignment"
echo "3. Share with students"
